### PR TITLE
Refactor properties loading + Bump Spring-Boot 3.2.2

### PR DESCRIPTION
**Pull request by zorglube**

### CODE REVIEW

**Comment by zorglube** [comment]
@lbruun It's ready for a review.

**Comment by zorglube** [comment]
@lbruun can you have a look in the PR, please.

**Comment by lbruun** [comment]
This PR was auto-closed by GitHub because the default branch was changed from `master` to `main`. This unintentionally closed PRs open at the time.

However, some of this is now implemented in v1.5.1:

- Spring Boot 3.2.6 is now used
- Spring Boot properties metadata are now generated
- The project now uses Google Style Formatting. See the the [CONTRIBUTION.md](CONTRIBUTION.md) file. A check has also been integrated into the GitHub CI workflow so that the workflow fails if files are not formatted according to the style rules.
- The project's CI workflow has been completely re-written. Releasing to Maven Central is now done from the CI workflow, not from developer's workstation.

**Comment by zorglube** [comment]
> This PR was auto-closed by GitHub because the default branch was changed from `master` to `main`. This unintentionally closed PRs open at the time.
> 
> However, some of this is now implemented in v1.5.1:
> 
> * Spring Boot 3.2.6 is now used
> * Spring Boot properties metadata are now generated
> * The project now uses Google Style Formatting. See the the [CONTRIBUTION.md](CONTRIBUTION.md) file. A check has also been integrated into the GitHub CI workflow so that the workflow fails if files are not formatted according to the style rules.
> * The project's CI workflow has been completely re-written. Releasing to Maven Central is now done from the CI workflow, not from developer's workstation.

Ok ! thank for the explantation.

**Pull request closed without merging**
